name: Push on Master jobs
on:
  push:
    branches: [ master ]

jobs:
  automaticpublish:
    name: Automatic Mod Browser Publish Integration
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
       
      # Mod Browser integration
      - uses: JavidPack/tModLoaderPublishIntegration@v0.11.8.3
        with:
          STEAMID64: ${{secrets.76561198022077369}}
          MODBROWSERPASSPHRASE: ${{secrets.e00798d78c6edd9b008b3199188ef228}}
          MODNAME: Avtomatmod
